### ISSUE TITLE
Default Set of active profiles is empty

### ISSUE THREAD

**Issue by pk-work** [SAP/neonbee#103]
**Describe the bug**
Default Set of active profiles is empty, which results in not deploying custom verticles.

**To Reproduce**
Start NeonBee with custom verticles on the classpath. These verticles won't get deloyed.

**Expected behavior**
The custom verticles should be deployed.

**Environment:**

- NeonBee version `0.9.1`

**Comment by kristian** [comment]
Fixed with #106 and release 0.10.0
