### ISSUE TITLE
Load Hazelcast configuration from file

### ISSUE THREAD

**Issue by pk-work** [SAP/neonbee#169]
At the moment NeonBee only supports specifying Hazelcast configurations from classpath. It would be a benefit if NeonBee could also load Hazelcast configurations from a file path.

Currently the "resource" is loaded via `ClasspathXmlConfig` class but there is also a ` FileSystemXmlConfig` class. In `NeonBeeOptions` we need to distinguish between these to approaches.

Maybe `<config>.xml` loads from classpath and `file:<[path]/config>.xml` loads from file path. Or we can first try to load the resource from classpath and if it is not found fall back to file path.

What do you think?

**Comment by s4heid** [comment]
I like the idea to do both. First, try loading it from classpath. If not present, try reading it from the file system.
