### ISSUE TITLE
[Bug]: NeonBee cannot use Logback > 1.3.x

### ISSUE THREAD

**Issue by kristian** [SAP/neonbee#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When starting NeonBee w/ Logback > 1.3.x on the runtime classpath, NeonBee's `LoggerConfiguration` fails, because logback in version 1.3.x removed `org.slf4j.impl.StaticLoggerBinder`. I would either suggest bumping the dependency all together or stop using the impl. package to make it compatible to the public API.

### Expected Behavior

NeonBee to work with any Logback version on the runtime classpath.

### Environment

```markdown
- OS:
- Java:
- NeonBee:
```

**Comment by pk-work** [comment]
Done
