### ISSUE TITLE
Load NeonBee options upfront (follow-up discussion)

### ISSUE THREAD

**Issue by s4heid** [SAP/neonbee#95]
Since the initial assumption of loading the neonbee config before initialization in order to set custom micrometer options is no longer valid (see [comment](https://github.com/SAP/neonbee/pull/94#issuecomment-1005613669)), and because the code review of #94 showed that this topic has still some room for discussion, we decided to split things up:

- #94 now only concerns adding micrometer registries via `NeonBeeConfig`, as the config loading change is not a requirement (Micrometer registries can be modified during runtime).
- loading the config beforehand will be discussed in this issue as there are multiple ways how to do it. Some of them will be detailed out below.

## Ideas

The following ideas came up so far:

### 1. Load the NeonBee config blocking

|Pro ➕ |Contra ➖ |
|--------|-----------|
|simple, low-effort solution|requires introduction of [additional loading methods which are blocking](https://github.com/SAP/neonbee/commit/3ba595e4226f0a6308156021dacb593e6bb28d22#diff-5a965f3ee0dcc987d3704e27a483cd1e3c82f401e2799f76ee2f5910d1ff64e8R65-R83). Throughout the entire project quite some effort was spent to minimize blocking code wherever possible |
|loading config is anyways required||

### 2. Start a temporary Vert.x instance

As proposed by @kristian (see [comment](https://github.com/SAP/neonbee/pull/94#issuecomment-1005144194)), start a temporary Vert.x instance which will be shut-down again after loading the config and before starting NeonBee's Vert.x instance.

As pointed out by @pk-work in another discussion, the Vert.x instance might be useful for other things as well such as the Pre-Processor which could also make use of the Vert.x instance.

|Pro ➕ |Contra ➖ |
|--------|-----------|
|other Vert.x projects also use this pattern: e.g. https://vertx.io/docs/vertx-config/java/#_configuring_vert_x_itself|unknown impact on the performance|
|code would be more homogenous as we could implement the file operation non-blocking|feels weird to do this effort just because of a simple file read operation. in case we could use it for other (pre-processing?) operations as well, this doubt would be invalid.|

Maybe we should evaluate how big the actual overhead of starting a vertx instance. do we have any measurements?

## Additional Context

**Current state:** The `NeonBeeConfig` is [loaded non-blocking directly before booting](https://github.com/SAP/neonbee/blob/18feb6d7a43794d482473d63ca2df60ff98b84c3/src/main/java/io/neonbee/NeonBee.java#L244) up the NeonBee server. As the Vert.x instance has already been [created and configured](https://github.com/SAP/neonbee/blob/18feb6d7a43794d482473d63ca2df60ff98b84c3/src/main/java/io/neonbee/NeonBee.java#L221) before this step, configuration set in the `NeonBeeConfig` could not be used to configure the Vert.x options.

**Desired state:** Configurations from `NeonBeeConfig` should be loaded early such that things like vertx options can be modified with the configuration.

**Comment by kristian** [comment]
Option 2. was decided between NeonBee committers.

We also decided to in the same change, change the PreProcessor handling, changing the LaunchPreProcessor interface similar to the Vert.x AbstractVerticle implemention to:

default execute(NeonBeeOptions) {}
default execute(Vertx, NeonBeeOptions, Promise) { execute(options); promise.complete() }

**Comment by s4heid** [comment]
In theory, the pre-launch vertx instance could also be passed into the `load` method of the [MicrometerRegistryLoader](https://github.com/SAP/neonbee/blob/0b06e92bd99f60e8e2f73bc2f38cff926ae2b61d/src/main/java/io/neonbee/config/metrics/MicrometerRegistryLoader.java#L21) by applying the same pattern as @kristian wrote down for the `execute` method.

As secrets / configs are often passed into an application container via a file, it might be useful to have a vertx instance which allows to use non-blocking readFile methods when implementing the `MicrometerRegistryLoader`.
